import os

HANDLER_BASE_GROUP, HANDLER_C_GROUP = range(2)

WMB_ABS_PATH = os.path.relpath('.')

HOUR_IN_SECONDS = 60 * 60

DAY_IN_SECONDS = 24 * HOUR_IN_SECONDS

WEEK_IN_SECONDS = 7 * DAY_IN_SECONDS

YEAR_IN_SECONDS = 365 * DAY_IN_SECONDS
